version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    ports:
      - "${APP_PORT:-8080}:8080"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8080
